import { writable } from 'svelte/store';
// @ts-expect-error -- generated by wasm-bindgen
import type { EditorApi } from '../../../pkg/rustboard_wasm';

export interface Rectangle {
	id: number;
	position: { x: number; y: number };
	width: number;
	height: number;
}

export interface Ellipse {
	id: number;
	position: { x: number; y: number };
	radius_x: number;
	radius_y: number;
}

export interface Line {
	id: number;
	start: { x: number; y: number };
	end: { x: number; y: number };
}

export interface Arrow {
	id: number;
	start: { x: number; y: number };
	end: { x: number; y: number };
}

export interface Diamond {
	id: number;
	position: { x: number; y: number };
	width: number;
	height: number;
}

export const wasmLoaded = writable<boolean>(false);
export const editorApi = writable<EditorApi | null>(null);
export const viewportOffset = writable({ x: 0, y: 0});
export const zoom = writable<number>(1);

// shapes
export const rectangles = writable<Rectangle[]>([]);
export const selectedRectangles = writable<Rectangle[]>([]);
export const ellipses = writable<Ellipse[]>([]);
export const selectedEllipses = writable<Ellipse[]>([]);
export const lines = writable<Line[]>([]);
export const selectedLines = writable<Line[]>([]);
export const arrows = writable<Arrow[]>([]);
export const selectedArrows = writable<Arrow[]>([]);
export const diamonds = writable<Diamond[]>([]);
export const selectedDiamonds = writable<Diamond[]>([]);
