import { writable } from 'svelte/store';
// @ts-expect-error -- generated by wasm-bindgen
import type { EditorApi } from '../../../pkg/rustboard_wasm';

export interface Rectangle {
	id: number;
	position: { x: number; y: number };
	width: number;
	height: number;
	stroke_color?: string;
	fill_color?: string | null;
	line_width?: number;
	dash_pattern?: string;
	border_radius?: number;
	rotation_angle?: number;
	z_index?: number;
}

export interface Ellipse {
	id: number;
	position: { x: number; y: number };
	radius_x: number;
	radius_y: number;
	stroke_color?: string;
	fill_color?: string | null;
	line_width?: number;
	dash_pattern?: string;
	rotation_angle?: number;
	z_index?: number;
}

export interface Line {
	id: number;
	start: { x: number; y: number };
	end: { x: number; y: number };
	stroke_color?: string;
	line_width?: number;
	dash_pattern?: string;
	rotation_angle?: number;
	z_index?: number;
}

export interface Arrow {
	id: number;
	start: { x: number; y: number };
	end: { x: number; y: number };
	stroke_color?: string;
	line_width?: number;
	dash_pattern?: string;
	rotation_angle?: number;
	z_index?: number;
}

export interface Diamond {
	id: number;
	position: { x: number; y: number };
	width: number;
	height: number;
	stroke_color?: string;
	fill_color?: string | null;
	line_width?: number;
	dash_pattern?: string;
	border_radius?: number;
	rotation_angle?: number;
	z_index?: number;
}

export interface Path {
	id: number;
	points: Array<{ x: number; y: number }>;
	stroke_color?: string;
	line_width?: number;
	rotation_angle?: number;
	z_index?: number;
}

export interface Image {
	id: number;
	position: { x: number; y: number };
	width: number;
	height: number;
	image_data: string; // base64 data URL or URL
	rotation_angle?: number;
	z_index?: number;
}

export interface Group {
	id: number;
	element_ids: number[];
	rotation_angle?: number;
}

export const wasmLoaded = writable<boolean>(false);
export const editorApi = writable<EditorApi | null>(null);
export const viewportOffset = writable({ x: 0, y: 0 });
export const zoom = writable<number>(1);

// shapes
export const rectangles = writable<Rectangle[]>([]);
export const selectedRectangles = writable<Rectangle[]>([]);
export const ellipses = writable<Ellipse[]>([]);
export const selectedEllipses = writable<Ellipse[]>([]);
export const lines = writable<Line[]>([]);
export const selectedLines = writable<Line[]>([]);
export const arrows = writable<Arrow[]>([]);
export const selectedArrows = writable<Arrow[]>([]);
export const diamonds = writable<Diamond[]>([]);
export const selectedDiamonds = writable<Diamond[]>([]);
export const paths = writable<Path[]>([]);
export const selectedPaths = writable<Path[]>([]);
export const images = writable<Image[]>([]);
export const selectedImages = writable<Image[]>([]);
export const groups = writable<Group[]>([]);
export const selectedGroups = writable<Group[]>([]);
